# Position Settings
# Since TE's are rarely used for flex spots, I would advise not adding it to the flex position

league_size: 10

positions:
  - QB
  - RB
  - RB
  - WR
  - WR
  - TE
  - FLEX

# All values points per
scoring:
  passing_yard: .04 # 25 yards per point
  passing_touchdown: 4
  interception: -2
  rushing_yard: .1
  rushing_touchdown: 6
  receiving_yard: .1
  return_touchdown: 6
  two_point_conversion: 2
  fumble_lost: -2
  offensive_fumble_return_td: 6

#Postion to name of file
rankings:
  QB: "FantasyPros_2018_Draft_QB_Rankings.csv"
  RB: "FantasyPros_2018_Draft_RB_Rankings.csv"
  WR: "FantasyPros_2018_Draft_WR_Rankings.csv"
  TE: "FantasyPros_2018_Draft_TE_Rankings.csv"
  name_column: 2
  rank_column: 7
